INSERT INTO classificacao_tipo (classificacao_cod, classificacao_desc) VALUES
	('TÍPICO', 'PROJETO DE SINALIZAÇÃO COMUM'),
	('FISCALIZAÇÃO ELETRÔNICA', 'CONTEMPLA SINALIZAÇÃO DE FISCALIZAÇÃO ELETRÔNICA'),
	('CORREDOR', 'SÃO PROJETOS ONDE SÃO SINALIZADOS GRANDES CORREDORES'),
	('ÁREA', 'PROJETO QUE ABRANGE UMA ÁREA(BAIRRO)'),
	('OBRA', 'PROJETO COM SINALIZAÇÃO PRÉ OU PÓS OBRA'),
	('PROJETO ESCOLA', 'PROJETO DE SINALIZAÇÃO DE ESCOLA'),
	('CICLOFAIXA', 'PROJETO QUE CONTEMPLA CICLOFAIXA'),
	('LOMBADA CONCRETO', 'LOMBADA FÍSICA CONSTRUÍDA EM CONCRETO'),
	('LOMBADA TACHÃO', 'LOMBADA FÍSICA UTILIZANDO TACHÕES COMO REDUTORES DE VELOCIDADE'),
	('LOMBADA ECOLÓGICA', 'LOMBADA FÍSICA UTILIZANDO MATERIAL MODULAR COMO REDUTORES DE VELOCIDADE'),
	('TRAVESSIA ELEVADA', 'FAIXA DE PEDESTRE ELEVADA CONSTRUÍDA AO MESMO NÍVEL DO PASSEIO'),
	('VIDEOMONITORAMENTO', 'PROJETO COM SINALIZAÇÃO DE VÍDEO-MONITORAMENTO INDICANDO FISCALIZAÇÃO POR C MERAS'),
	('EQUINA SEGURA', 'PROJETO COM SINALIZAÇÃO COM TRATAMENTO DIFERENCIADO EM ALGUNS CRUZAMENTOS'),
	('ZONA AZUL', 'PROJETO COM SINALIZAÇÃO DE ZONA AZUL'),
	('FAIXA EXCLUSIVA', 'PROJETO DE CORREDOR COM SINALIZAÇÃO DE FAIXA EXCLUSIVA DE ÔNIBUS'),
	('SEMÁFORO VEICULAR', 'PROJETO COM IMPLANTAÇÃO DE SEMÁFORO VEICULAR'),
	('SEMÁFORO PEDESTRES', 'PROJETO COM IMPLANTAÇÃO DE SEMÁFORO PARA PEDESTRES'),
	('DEMARCAÇÃO GARAGEM', 'DEMARCAÇÃO DE ENTRADA E SAÍDA DE VEÍCULOS')
ON CONFLICT (classificacao_cod) DO NOTHING;

INSERT INTO descricao_tipo (descricao_cod, descricao_desc) VALUES
	('HORIZONTAL E VERTICAL', 'HORIZONTAL E VERTICAL'),
	('VERTICAL', 'VERTICAL'),
	('HORIZONTAL', 'HORIZONTAL'),
	('RENOVAÇÃO HORIZONTAL', 'RENOVAÇÃO HORIZONTAL'),
	('MANUTENÇÃO VERTICAL', 'REPOSIÇÃO, REFIXAÇÃO, SUBSTITUIÇÃO  DE PLACA'),
	('PLACA INFORMATIVA', 'PLACA INFORMATIVA MUDANÇA DE SENTIDO, PROIBIÇÃO DE CONVERSÃO, ETC'),
	('DISPOSITIVOS AUXILIARES', 'TACHÃO, GELITO, GELO, BALIZADORES')
ON CONFLICT (descricao_cod) DO NOTHING;

INSERT INTO situacao_tipo (situacao_cod, situacao_desc) VALUES
	('GCE', 'PROJETO COM A GCE'),
	('EQUIPE AMC', 'PROJETO COM A EQUIPE DA AMC'),
	('CONTRATADA', 'PROJETO COM A CONTRATADA'),
	('ANDAMENTO', 'PROJETO EM ANDAMENTO'),
	('VISTORIA CONTRATADA', 'PROJETO PARA VISTORIA CONTRATADA'),
	('VISTORIA AMC', 'PROJETO PARA VISTORIA AMC'),
	('PENDÊNCIA', 'PROJETO COM PENDÊNCIA'),
	('SUSPENSO', 'PROJETO SUSPENSO AGUARDANDO DEFINIÇÃO, AUTORIZAÇÃO OU OBRA FÍSICA'),
	('CONCLUÍDO', 'PROJETO CONCLUÍDO'),
	('CANCELADO', 'PROJETO CANCELADO')
ON CONFLICT (situacao_cod) DO NOTHING;

INSERT INTO motivo_tipo (motivo_cod, motivo_desc) VALUES
	('SUPERINTENDÊNCIA', 'SOLICITAÇÃO DA SUPERINTENDÊNCIA'),
	('ADJUNTO SUPERINTENDÊNCIA', 'SOLICITAÇÃO SUPERINTENDENTE ADJUNTO'),
	('NUTRAN', 'SOLICITAÇÃO DO NUTRAN'),
	('GEENG', 'SOLICITAÇÃO DA GERÊNCIA DE ENGENHARIA'),
	('GERÊNCIA/COORDENAÇÃO','SOLICITAÇÃO DAS DEMAIS GERÊNCIAS/COORDENAÇÕES'),
	('SIAT/ACIDENTES','SOLICITAÇÃO SIAT/OCORRÊNCIA DE ACIDENTES'),
	('CTAFOR', 'SOLICITAÇÃO CTAFOR'),
	('GEOFI', 'SOLICITAÇÃO GEOFI'),
	('IMPRENSA', 'SOLICITAÇÃO IMPRENSA'),
	('RECAPE','SOLICITAÇÃO RECAPE'),
	('SECRETARIA DE CONSERVAÇÃO', 'SOLICITAÇÃO DA SECRETARIA DE CONSERVAÇÃO'),
	('PAITT', 'SOLICITAÇÃO PAITT'),
	('SEINF', 'SOLICITAÇÃO SEINF'),
	('VEREADOR', 'SOLICITAÇÃO DE VEREADOR'),
	('DEPUTADO', 'SOLICITAÇÃO DE DEPUTADO'),
	('PREFEITO', 'SOLICITAÇÃO DO PREFEITO/GABINETE'),
	('SECRETARIAS/REGIONAIS', 'SOLICITAÇÃO DAS SECRETARIAS E REGIONAIS'),
	('MINISTÉRIO PÚBLICO', 'SOLICITAÇÃO DO MINISTÉRIO PÚBLICO'),
	('DETRAN','SOLICITAÇÃO DETRAN'),
	('OUTROS','OUTROS SOLICITANTES')
ON CONFLICT (motivo_cod) DO NOTHING;

INSERT INTO aparelho_tipo (aparelho_cod, aparelho_desc) VALUES
	('SH-MEC', 'SINALIZAÇÃO HORIZONTAL MECÂNICA'),
	('SH-MAN', 'SINALIZAÇÃO HORIZONTAL MANUAL'),
	('SV','SINALIZAÇÃO VERTICAL'),
	('PLACA', 'PLACA'),
	('COL-SIM', 'COLUNA SIMPLES'),
	('COL-CIL', 'COLUNA CILÍNDRICA DE BRAÇO PROJETADO'),
	('COL-CON', 'COLUNA CÔNICA DE BRAÇO PROJETADO'),
	('BP-POSTE', 'BRAÇO PROJETADO PARA POSTE'),
	('TCH-BI', 'TACHÕES BIDIRECIONAIS'),
	('TCH-MONO', 'TACHÕES MONODIRECIONAIS'),
	('BALIZADORES', 'BALIZADORES')
ON CONFLICT (aparelho_cod) DO NOTHING;

INSERT INTO intervencao_tipo (intervencao_cod, intervenca_desc) VALUES
	('CSHV', 'CRUZAMENTO SINALIZADO HORIZONTAL E VERTICAL'),
	('CSH', 'CRUZAMENTO SINALIZADO HORIZONTAL'),
	('CSV', 'CRUZAMENTO SINALIZADO VERTICAL'),
	('CS-TCH', 'CRUZAMENTO SINALIZADO COM TACHÃO'),
	('CS-ES', 'CRUZAMENTO SINALIZADO - ESQUINA SEGURA'),
	('CS-ES2.0', 'CRUZAMENTO SINALIZADO - ESQUINA SEGURA 2.0'),
	('PE', 'PROJETO ESCOLA'),
	('TP', 'TRAVESSIA DE PEDESTRES'),
	('FPX', 'FAIXA DE PEDESTRES EM X'),
	('US', 'UNIDADE DE SAÚDE'),
	('ISV', 'IMPLANTAÇÃO DE SEMÁFORO VEICULAR'),
	('ISP', 'IMPLANTAÇÃO DE SEMÁFORO PARA PEDESTRES'),
	('PC', 'PROJETO CORREDOR'),
	('PA', 'PROJETO ÁREA'),
	('FE', 'FISCALIZAÇÃO ELETRÔNICA'),
	('VR', 'VIA RECAPEADA'),
	('MS', 'MUDANÇA DE SENTIDO'),
	('MP', 'MUDANÇA DE PREFERENCIAL'),
	('TCH', 'TACHÕES'),
	('TE', 'TRAVESSIA ELEVADA'),
	('LC', 'LOMBADA FÍSICA DE CONCRETO'),
	('LTCH', 'LOMBADA FÍSICA DE TACHÃO'),
	('LE', 'LOMBADA FÍSICA ECOLÓGICA'),
	('AEMN', 'ÁREA DE ESPERA DE MOTOS NOVA'),
	('AEMR', 'ÁREA DE ESPERA DE MOTOS RENOVADA'),
	('AEMA', 'ÁREA DE ESPERA DE MOTOS APAGADA'), 
	('DG', 'DEMARCAÇÃO DE GARAGEM'),
	('VZAN', 'VAGA DE ZONA AZUL NOVA'),
	('VZAR', 'VAGA DE ZONA AZUL RENOVADA'),
	('VZAAP', 'VAGA DE ZONA AZUL APAGADA'),
	('VIN-ZA', 'VAGA DE IDOSO NOVA - ZONA AZUL'),
	('VIR-ZA', 'VAGA DE IDOSO RENOVADA - ZONA AZUL'),
	('VIAP-ZA', 'VAGA DE IDOSO APAGADA - ZONA AZUL'),
	('VDN-AZ', 'VAGA DE DEFICIENTE NOVA - ZONA AZUL'),
	('VDR-ZA', 'VAGA DE DEFICIENTE RENOVADA - ZONA AZUL'),
	('VDAP-ZA', 'VAGA DE DEFICIENTE APAGADA - ZONA AZUL'),
	('VCDN-ZA', 'VAGA DE CARGA E DESCARGA NOVA - ZONA AZUL'),
	('VCDR-ZA', 'VAGA DE CARGA E DESCARGA RENOVADA - ZONA AZUL'),
	('VCDAP-ZA', 'VAGA DE CARGA E DESCARGA APAGADA - ZONA AZUL'),
	('VDN', 'VAGA DE DEFICIENTE NOVA'),
	('VDR', 'VAGA DE DEFICIENTE RENOVADA'),
	('VDAP', 'VAGA DE DEFICIENTE APAGADA'),
	('VIN', 'VAGA DE IDOSO NOVA'),
	('VIR', 'VAGA DE IDOSO RENOVADA'),
	('VIAP', 'VAGA DE IDOSO APAGADA'),
	('VCDN', 'VAGA DE CARGA E DESCARGA NOVA'),
	('VCDR', 'VAGA DE CARGA E DESCARGA RENOVADA'),
	('VCDAP', 'VAGA DE CARGA E DESCARGA APAGADA'),
	('VEDN', 'VAGA DE EMBARQUE E DESEMBARQUE NOVA'),
	('VEDR', 'VAGA DE EMBARQUE E DESEMBARQUE RENOVADA'),
	('VEDA', 'VAGA DE EMBARQUE E DESEMBARQUE APAGADA'),
	('VTN', 'VAGA DE TÁXI NOVA'),
	('VTR', 'VAGA DE TÁXI RENOVADA'),
	('VTAP', 'VAGA DE TÁXI APAGADA'),
	('VMTN', 'VAGA DE MOTO TÁXI NOVA'),
	('VMTR', 'VAGA DE MOTO TAXI RENOVADA'),
	('VMTAP', 'VAGA DE MOTOTAXI APAGADA'),
	('VMN', 'VAGA DE MOTO NOVA'),
	('VMR', 'VAGA DE MOTO RENOVADA'),
	('VMAP', 'VAGA DE MOTO APAGADA'),
	('VAN', 'VAGA DE AMBUL NCIA NOVA'),
	('VAR', 'VAGA DE AMBUL NCIA RENOVADA'),
	('VAAP', 'VAGA DE AMBUL NCIA APAGADA'),
	('VON', 'VAGA DE ÔNIBUS NOVA'),
	('VOR', 'VAGA DE ÔNIBUS RENOVADA'),
	('VOAP', 'VAGA DE ÔNIBUS APAGADA'),
	('VVON', 'VAGA DE VEÍCULO OFICIAL NOVA'),
	('VVOR', 'VAGA DE VEÍCULO OFICIAL RENOVADA'),
	('VVOAP', 'VAGA DE VEÍCULO OFICIAL APAGADA'),
	('VVAPN', 'VAGA DE VEÍCULO AUTOMOTOR PARTICULAR NOVA'),
	('VVAPR', 'VAGA DE VEÍCULO AUTOMOTOR PARTICULAR RENOVADA'),
	('VVAPAP', 'VAGA DE VEÍCULO AUTOMOTOR PARTICULAR APAGADA'),
	('VTEN', 'VAGA DE TRANSPORTE ESCOLAR NOVA'),
	('VTER', 'VAGA DE TRANSPORTE ESCOLAR RENOVADA'),
	('VTEAP', 'VAGA DE TRANSPORTE ESCOLAR APAGADA'),
	('VVVN', 'VAGA DE VEÍCULO DE VALORES NOVA'),
	('VVVR', 'VAGA DE VEÍCULO DE VALORES RENOVADA'),
	('VVVAP', 'VAGA DE VEÍCULO DE VALORES APAGADA'),
	('OVN', 'OUTRAS VAGAS NOVAS'),
	('OVR', 'OUTRAS VAGAS RENOVADAS'),
	('OVAP', 'OUTRAS VAGAS APAGADAS'),
	('YB','YELLOW BOX')
ON CONFLICT (intervencao_cod) DO NOTHING;

INSERT INTO projetos_tipo (tipo_cod, tipo_desc) VALUES
	('PONTUAL', 'PROJETO PONTUAL CONTRATADA'),
	('MACRO', 'PROJETO MACRO CONTRATADA'),
	('MANUTENÇÃO', 'PROJETO MANUTENÇÃO AMC')
ON CONFLICT (tipo_cod) DO NOTHING;

INSERT INTO setores (setor_cod, setor_desc) VALUES
	('GPO1', 'GERÊNCIA DE PROJETOS OPERACIONAIS 1'),
	('GPO2', 'GERÊNCIA DE PROJETOS OPERACIONAIS 2'),
	('GCO', 'GERÊNCIA DE CONTROLE DE OBRAS'),
	('GPE', 'GERÊNCIA DE PROJETOS ESPECIAIS')
ON CONFLICT (setor_cod) DO NOTHING;

INSERT INTO autorizacoes (autoriza_cod, autoriza_desc) VALUES
	('ROLE_ADMIN', 'ADMINISTRADOR DO SISTEMA'),
	('ROLE_SUBADMIN', 'ACESSO A MAIORIA DAS FUNÇÕES ADMINISTRATIVAS'),
	('ROLE_USUARIO', 'ACESSO BÁSICO')
ON CONFLICT (autoriza_cod) DO NOTHING;

INSERT INTO usuarios (usuario_nm, cpf_num, setor_id, email, senha, mail_warn) VALUES
	('JUNIOR', '03577488328', (SELECT setor_id FROM setores WHERE setor_cod = 'GPE'), 'jose.lima@fortaleza.ce.gov.br', 
	'$2y$10$fSFQKUwqrGc4oSS8AIe/6.xQZ4Phhoo1un4DTigHmQ3JHomP1S09S', true)
ON CONFLICT (cpf_num) DO NOTHING;
INSERT INTO permissoes (usuario_id, autoriza_cod) SELECT 1, 'ROLE_ADMIN';


INSERT INTO SIGA.APARELHO_TIPO (APARELHO_COD, APARELHO_DESC) VALUES ('TESTE', 'TESTE');
SELECT APARELHO_COD, APARELHO_DESC FROM SIGA.APARELHO_TIPO;
DELETE FROM SIGA.APARELHO_TIPO WHERE APARELHO_COD = 'TESTE';
UPDATE SIGA.APARELHO_TIPO SET APARELHO_DESC = 'TESTE2' WHERE APARELHO_COD ='TESTE';
SELECT APARELHO_COD, APARELHO_DESC FROM SIGA.APARELHO_TIPO WHERE APARELHO_COD = 'TCH-BI';

SELECT * FROM SIGA.APARELHO_TIPO WHERE aparelho_cod = "";

select count(*) from siga.aparelho_tipo