INSERT INTO classificac_tipo (classificac_code, classificac_espec) VALUES
	('TIPICO', 'PROJETO DE SINALIZAÇÃO COMUM'),
	('FE', 'CONTEMPLA SINALIZAÇÃO DE FISCALIZAÇÃO ELETRÔNICA'),
	('CORREDOR', 'SÃO PROJETOS ONDE SÃO SINALIZADOS GRANDES CORREDORES (AVENIDAS/RUAS)'),
	('AREA', 'PROJETO QUE ABRANGE UMA ÁREA(BAIRRO)'),
	('OBRA', 'PROJETO COM SINALIZAÇÃO PRÉ OU PÓS OBRA'),
	('PE', 'PROJETO DE SINALIZAÇÃO DE ESCOLA'),
	('CICLO', 'PROJETO QUE CONTEMPLA CICLOFAIXA'),
	('LFC', 'LOMBADA FÍSICA CONSTRUIDA EM CONCRETO'),
	('LFT', 'LOMBADA FÍSICA UTILIZANDO TACHÕES COMO REDUTORES DE VELOCIADADE'),
	('FPE', 'FAIXA DE PEDESTRE CONSTRUÍDA AO MESMO NÍVEL DO PASSEIO'),
	('VM', 'PROJETO COM SINALIZAÇÃO DE VIDEO-MONITORAMENTO INDICANDO FISCALIZAÇÃO POR CÂMERAS'),
	('ES', 'PROJETO COM SINALIZAÇÃO COM TRATAMENTO DIFERENCIADO EM ALGUNS CRUZAMENTOS'),
	('ZA', 'PROJETO COM SINALIZAÇÃO DE ZONA AZUL'),
	('FEO', 'PROJETO DE CORREDOR COM SINALIZAÇÃO DE FAIXA EXCLUSIVA DE ÔNIBUS'),
	('SV', 'PROJETO COM IMPLATAÇÃO DE SEMÁFORO VEICULAR'),
	('SP', 'PROJETO COM IMPLANTAÇÃO DE SEMÁFORO PARA PEDESTRES')
ON CONFLICT (classificac_code) DO NOTHING;

INSERT INTO descricao_tipo (descricao_code, descricao_espec) VALUES
	('HORIZONTAL E VERTICAL', 'HORIZONTAL E VERTICAL'),
	('VERTICAL', 'VERTICAL'),
	('HORIZONTAL', 'HORIZONTAL'),
	('RENOVACAO HORIZONTAL', 'RENOVAÇÃO HORIZONTAL'),
	('RRPOSICAO PLACA', 'REPOSIÇÃO DE PLACA'),
	('FIXAR PLACA', 'FIXAR PLACA'),
	('SSUBSTITUICAO DE PLACA', 'SUBSTITUIÇÃO DE PLACA'),
	('REPOSICAO DE GELITO', 'REPOSIÇÃO DE GELITO'),
	('ORIENTACAO TURISTICA', 'ORIENTAÇÃO TURISTICA'),
	('FAIXA INFORMATIVA', 'FAIXA INFORMATIVA')
ON CONFLICT (descricao_code) DO NOTHING;

INSERT INTO situacao_tipo (situacao_code, situacao_espec) VALUES
	('VISTORIA CONTRATADA', ''),
	('VISTORIA AMC', ''),
	('PENDÊNCIA', ''),
	('AGUARDANDO',''),
	('VISTORIA AMC - PENDÊNCIA', ''),
	('CANCELADO', ''),
	('SUSPENSO', ''),
	('CONCLUIDO', '')
ON CONFLICT (situacao_code) DO NOTHING;

INSERT INTO motivo_tipo (motivo_code, motivo_espec) VALUES
	('PRESIDENCIA', ''),
	('NUTRAN', ''),
	('DIENG', ''),
	('GERENCIA',''),
	('CTAFOR', ''),
	('GEOFI', ''),
	('RECAPE',''),
	('FE', ''),
	('SEMAFORO', ''),
	('SCSP', ''),
	('SEINF', ''),
	('VEREADOR', ''),
	('GAB.PREF', ''),
	('DETRAN',''),
	('OUTROS','')
ON CONFLICT (motivo_code) DO NOTHING;

INSERT INTO aparelho_tipo (aparelho_code, aparelho_espec) VALUES
	('SH-MEC', 'SINALIZAÇÃO HORIZONTAL MECÂNICA'),
	('SH-MAN', 'SINALIZAÇÃO HORIZONTAL MANUAL'),
	('SV','SINALIZAÇÃO VERTICAL'),
	('PLACA', 'PLACA'),
	('COL-SIM', 'COLUNA SIMPLES'),
	('COL-CIL', 'COLUNA CILÍNDRICA DE BRAÇO PROJETADO'),
	('COL-CON', 'COLUNA CÔNICA DE BRAÇO PROJETADO'),
	('BP-POSTE', 'BRAÇO PROJETADO PARA POSTE')
ON CONFLICT (aparelho_code) DO NOTHING;

INSERT INTO intervencao_tipo (intervencao_code, intervenca_espec) VALUES
	('PE', 'PROJETO ESCOLA'),
	('CSHV', 'CRUZAMENTO SINALIZADO HORIZONTAL VERTICAL'),
	('CSH', 'CRUZAMENTO SINALIZADO HORIZONTAL'),
	('CSV', 'CRUZAMENTO SINALIZADO VERTICAL'),
	('TP', 'TRAVESSIA DE PEDESTRES'),
	('US', 'UNIDADE DE SAUDE'),
	('VTN', 'VAGA DE TÁXI NOVA'),
	('VTR', 'VAGA DE TÁXI RENOVADA'),
	('VTAP', 'VAGA DE TÁXI APAGADA'),
	('VDN', 'VAGA DE DEFICIENTE NOVA'),
	('VDR', 'VAGA DE DEFICIENTE RENOVADA'),
	('VDAP', 'VAGA DE DEFICIENTE APAGADA'),
	('VZAN', 'VAGA DE ZONA AZUL NOVA'),
	('VZAR', 'VAGA DE ZONA AZUL RENOVADA'),
	('VZAAP', 'VAGA DE ZONA AZUL APAGADA'),
	('VMTN', 'VAGA DE MOTO TAXI NOVA'),
	('VMTR', 'VAGA DE MOTO TAXI RENOVADA'),
	('VMTAP', 'VAGA DE MOTO TAXI APAGADA'),
	('VMN', 'VAGA DE MOTO NOVA'),
	('VMR', 'VAGA DE MOTO RENOVADA'),
	('VMAP', 'VAGA DE MOTO APAGADA'),
	('VAN', 'VAGA DE AMBULÂNCIA NOVA'),
	('VAR', 'VAGA DE AMBULÂNCIA RENOVADA'),
	('VAAP', 'VAGA DE AMBULÂNCIA APAGADA'),
	('VON', 'VAGA DE ÔNIBUS NOVA'),
	('VOR', 'VAGA DE ÔNIBUS RENOVADA'),
	('VOAP', 'VAGA DE ÔNIBUS APAGADA'),
	('VCDN', 'VAGA DE CARGA E DESCARGA NOVA'),
	('VCDR', 'VAGA DE CARGA E DESCARGA RENOVADA'),
	('VCDAP', 'VAGA DE CARGA E DESCARGA APAGADA'),
	('VVON', 'VAGA DE VEÍCULO OFICIAL NOVA'),
	('VVOR', 'VAGA DE VEÍCULO OFICIAL RENOVADA'),
	('VVOAP', 'VAGA DE VEICULO OFICIAL APAGADA'),
	('VVAPN', 'VAGA DE VEÍCULO AUTOMOTOR NOVA'),
	('VVAPR', 'VAGA DE VEÍCULO AUTOMOTOR RENOVADA'),
	('VVAPAP', 'VAGA DE VEÍCULO AUTOMOTOR APAGADA'),
	('VTEN', 'VAGA DE TRANSPORTE ESCOLAR NOVA'),
	('VTER', 'VAGA DE TRANSPORTE ESCOLAR RENOVADA'),
	('VTEAP', 'VAGA DE TRANSPORTE ESCOLAR APAGADA'),
	('VVVN', 'VAGA DE VEÍCULO DE VALORES NOVA'),
	('VVVR', 'VAGA DE VEÍCULO DE VALORES RENOVADA'),
	('VVVAP', 'VAGA DE VEÍCULO DE VALORES APAGADA'),
	('OVN', 'OUTRAS VAGAS NOVAS'),
	('OVR', 'OUTRAS VAGAS RENOVADAS'),
	('OVAP', 'OUTRAS VAGAS APAGADAS'),
	('VIN', 'VAGA DE IDOSO NOVA'),
	('VIR', 'VAGA DE IDOSO RENOVADA'),
	('VIAP', 'VAGA DE IDOSO APAGADA'),
	('IS', 'IMPLATAÇÃO DE SEMÁFORO'),
	('ISP', 'IMPLANTAÇÃO DE SEMÁFORO PARA PEDESTRES'),
	('PC', 'PROJETO CORREDOR'),
	('PA', 'PROJETO ÁREA'),
	('FE', 'FISCALIZAÇÃO ELETRÔNICA'),
	('VR', 'VIA RECAPEADA'),
	('MS', 'MUDANÇA DE SENTIDO'),
	('MP', 'MUDANÇA DE PREFERENCIAL'),
	('ED', 'EMBARQUE E DESEMBARQUE'),
	('TCH', 'TACHÕES'),
	('TF', 'TRAVESSIA FÍSICA'),
	('LE', 'LOMBADA ELEVADA')
ON CONFLICT (intervencao_code) DO NOTHING;

INSERT INTO projetos_tipo (tipo_code, tipo_espec) VALUES
	('PONTUAL', ''),
	('MACRO', ''),
	('MANUTENÇÃO','')
ON CONFLICT (tipo_code) DO NOTHING;

INSERT INTO setores (setor_cod, setor_desc) VALUES
	('GPO1', 'GERÊNCIA DE PROJETOS 1'),
	('GP02', 'GERÊNCIA DE PROJETOS 2'),
	('GCO', 'GERÊNCIA DE CONTROLE DE OPERAÇÕES'),
	('GCE', '')
ON CONFLICT (setor_cod) DO NOTHING;







--------------------------------------------------------------


INSERT INTO setores (setor_cod, setor_desc) VALUES
	('DITRAN', 'DIRETORIA DE TRÂNSITO'),
	('DIAF', 'DIRETORIA ADMINISTRATIVA E FINANCEIRA'),
	('NUTEC', 'NÚCLEO DE TECNOLOGIA'),
	('GEOFI', 'GERÊNCIA DE OPERAÇÃO E FISCALIZAÇÃO'),
	('SEVIM', 'SETOR DE VIATURAS'),
	('CELOG', 'CÉLULA DE LOGISTICA E CARGAS'), 
	('NUCAD', 'NUCLEO DE CADASTRAMENTO'),
	('NUDAP', 'NÚCLEO DE DESENVOLVIMENTO DE APLICAÇÕES'),
	('PROJUR', 'PROCURADORIA JURÍDICA')
ON CONFLICT (setor_cod) DO NOTHING;

INSERT INTO autorizacoes (autoriza_cod, autoriza_desc) VALUES
	('ROLE_ADMIN', 'ADMINISTRADOR DO SISTEMA'),
	('ROLE_SUBADMIN', 'ACESSO A MAIORIA DAS FUNÇÕES ADMINISTRATIVAS'),
	('ROLE_USUARIO', 'ACESSO BÁSICO')
ON CONFLICT (autoriza_cod) DO NOTHING;

INSERT INTO usuarios (usuario_nm, cpf_num, setor_id, email, senha, mail_warn) VALUES
	('JOSE ONILTON JUNIOR', '03577488328', (SELECT setor_id FROM setores WHERE setor_cod = 'NUDAP'),'jose.lima@fortaleza.ce.gov.br', 
	'$2y$10$fSFQKUwqrGc4oSS8AIe/6.xQZ4Phhoo1un4DTigHmQ3JHomP1S09S', true)
ON CONFLICT (cpf_num) DO NOTHING;

INSERT INTO permissoes (usuario_id, autoriza_cod) SELECT 1, 'ROLE_ADMIN';		
		
SELECT u.usuario_id, u.usuario_nm, u.cpf_num, u.mat_num, u.email, u.senha, u.mail_warn, 
p.autoriza_cod, u.setor_id, s.setor_cod, s.setor_desc
FROM usuarios u 
LEFT JOIN permissoes p ON u.usuario_id = p.usuario_id 
LEFT JOIN setores s ON u.setor_id = s.setor_id;

TRUNCATE CASCADE usuarios
RESTART IDENTITY;

ALTER SEQUENCE usuarios RESTART WITH 1;
UPDATE t SET idcolumn=nextval('seq');
		
		